env:
  DOCKER_IMAGE=matshareyourscript/aws-helm-kubectl
  DOCKER_TAG=2.3.0

services:
  - docker

script:
  - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  - docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$DOCKER_TAG

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$DOCKER_TAG
  - docker push $DOCKER_IMAGE:latest
